version: '3.2'
services:
  dev:
    build: .
    volumes:
      - type: bind
        source: .
        target: /home/tls_demo
      - type: bind
        source: ../build_docker_tls_demo
        target: /home/build_tls_demo
    # stdin_open: true      # Same as --interactive

    # Bash ignores SIGTERM, which Docker uses by default to terminate containers.
    # Bash will exit by default on SIGHUP - terminal hangup - so attach a TTY and hangup to stop containers.
    # Alternatively, you could run a bash script and configure a trap to exit on SIGTERM.
    tty: true
    stop_signal: SIGHUP
